name: jobs

on: push

jobs:
  validate-html:
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest

    steps:
      - name: Get repo code
        uses: actions/checkout@v4

      - name: Validate HTML file
        run: test -f index.html

  validate-js:
    runs-on: ubuntu-latest

    steps:
      - name: Get repo code
        uses: actions/checkout@v4

      - name: Validate JS file
        run: test -f script.js

      - name: Validate JS code
        run: node --check script.js

  validate-code:
    needs: [validate-html, validate-js]
    runs-on: ubuntu-latest

    steps:
      - name: Get repo code
        uses: actions/checkout@v4

      - name: Validate JS code
        run: node --check script.js

      - name: Validate HTML file
        run: npx htmlhint index.html
